import type { AppSettings, Resource, WeeklySchedule } from './types'

export const defaultSettings: AppSettings = {
  id: 'default',
  childName: '小朋友',
  childBirthYear: 2021,
  childBirthMonth: 11,
  childAvatarId: 'rose-princess',
  dailyIntensity: 'standard',
  targetMinMinutes: 45,
  targetMaxMinutes: 75,
}

export const defaultResources: Resource[] = [
  {
    id: 'abc-reading-raz',
    name: 'ABC Reading for RAZ',
    type: 'app',
    abilities: ['reading'],
    defaultMinutes: 20,
    enabled: true,
    color: '#1f6f5f',
    notes: 'RAZ 分级阅读',
  },
  {
    id: 'oxford-tree',
    name: '牛津树',
    type: 'graded-reader',
    abilities: ['reading'],
    defaultMinutes: 20,
    enabled: true,
    color: '#5f7f54',
    notes: '亲子分级阅读',
  },
  {
    id: 'lingostar',
    name: 'Lingostar',
    type: 'live-class',
    abilities: ['class', 'speaking'],
    defaultMinutes: 25,
    enabled: true,
    color: '#b75a6b',
    notes: '25 分钟 1 对 1 外教课',
  },
  {
    id: 'push-up',
    name: 'Push up',
    type: 'live-class',
    abilities: ['class', 'speaking'],
    defaultMinutes: 90,
    enabled: true,
    color: '#8d6a4a',
    notes: '1.5 小时外教大课',
  },
  {
    id: 'peppa-pig',
    name: '小猪佩奇',
    type: 'audio-video',
    abilities: ['listening'],
    defaultMinutes: 15,
    enabled: true,
    color: '#3f73a8',
    notes: '动画熏听',
  },
  {
    id: 'bluey',
    name: '布鲁伊',
    type: 'audio-video',
    abilities: ['listening'],
    defaultMinutes: 15,
    enabled: true,
    color: '#4f8094',
    notes: '动画熏听',
  },
  {
    id: 'little-fox',
    name: 'Little Fox',
    type: 'audio-video',
    abilities: ['listening'],
    defaultMinutes: 20,
    enabled: true,
    color: '#6c6f9e',
    notes: '故事熏听',
  },
  {
    id: 'numberblocks',
    name: 'Numberblocks',
    type: 'audio-video',
    abilities: ['listening'],
    defaultMinutes: 15,
    enabled: true,
    color: '#c4833f',
    notes: '数字主题熏听',
  },
]

export const defaultSchedules: WeeklySchedule[] = [
  {
    id: 'schedule-lingostar-tue',
    weekday: 2,
    startTime: '18:30',
    resourceId: 'lingostar',
    minutes: 25,
    enabled: true,
  },
  {
    id: 'schedule-lingostar-thu',
    weekday: 4,
    startTime: '18:30',
    resourceId: 'lingostar',
    minutes: 25,
    enabled: true,
  },
  {
    id: 'schedule-push-up-mon',
    weekday: 1,
    startTime: '09:30',
    resourceId: 'push-up',
    minutes: 90,
    enabled: true,
  },
]
